name:                vogelnest-backend
version:             0.1.0.0
github:              "studieren-ohne-grenzen/vogelnest-backend"
license:             BSD3
author:              "Linus Heck"
copyright:           "2020 Études sans frontières - Studieren Ohne Grenzen Deutschland e.V."

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/vogelnest-backend#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- servant
- servant-server
- warp
- ldap-client == 0.4.0
- text
- ini
- either

library:
  source-dirs: src

executables:
  vogelnest-backend-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vogelnest-backend

tests:
  vogelnest-backend-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vogelnest-backend
